server:
  port: 9102

spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    default-schema: spring_cloud_demo
    drop-first: false
    enabled: ${liquibase_enable:true}
  cloud:
    stream:
      bindings:
        cancel_reservation_input:
          binder: rabbit
          destination: cancel-reservation
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3

---
spring:
  profiles: development

---
spring:
  profiles: k8s