apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
          type: Directory
      containers:
      - name: api
        image: registry.gavin.com/api:latest
        imagePullPolicy: Always
        ports:
        - name: rest-port
          containerPort: 8002
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
        - mountPath: /opt/log/stash
          name: log-volume

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8002
    nodePort: 30802