apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
          type: Directory
      containers:
      - name: auth
        image: registry.gavin.com/auth:latest
        imagePullPolicy: Always
        ports:
        - name: rest-port
          containerPort: 9999
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
        - mountPath: /opt/log/stash
          name: log-volume

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: auth
spec:
  selector:
    app: auth
  ports:
  - port: 9999