apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: filebeat
  template:
    metadata:
      labels:
        name: filebeat
    spec:
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
      containers:
      - name: filebeat
        image: gaven/filebeat:5.5.0
        env:
        - name: ELASTICSEARCH_ENDPOINT
          value: "192.168.1.80:9200"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log-volume
          mountPath: /input
          readOnly: true

