apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
          type: Directory
      containers:
      - name: order
        image: registry.gavin.com/order:latest
        imagePullPolicy: Always
        ports:
        - name: rest-port
          containerPort: 9103
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
        - mountPath: /opt/log/stash
          name: log-volume
        livenessProbe:
          httpGet:
            path: /ping
            port: rest-port
          initialDelaySeconds: 15
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: order
spec:
  selector:
    app: order
  ports:
  - port: 9103