apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: product
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
          type: Directory
      containers:
      - name: product
        image: registry.gavin.com/product:latest
        imagePullPolicy: Always
        ports:
        - name: rest-port
          containerPort: 9102
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
        - mountPath: /opt/log/stash
          name: log-volume
        livenessProbe:
          httpGet:
            path: /ping
            port: rest-port
          initialDelaySeconds: 15
          timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: product
spec:
  selector:
    app: product
  ports:
  - port: 9102