server:
  port: 9999
  context-path: /uaa # 此处必须设定否则无法获得token

security:
  user:
    name: gavin
    password: gavin
  basic:
    enabled: false

#management:
#  security:
#    enabled: false

feign:
  hystrix:
    enabled: true

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: spring_cloud_demo
  drop-first: false
  enabled: ${liquibase_enable:true}

logging:
  level:
    org.springframework.security: DEBUG
    com.gavin.common.client.UserClient: DEBUG

---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_demo?useUnicode=true&useSSL=false&amp;characterEncoding=utf8
    username: root
    password: root

---
spring:
  profiles: k8s
  redis:
    host: ${redis_host}
    port: ${redis_port}
    database: 0
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql_host}:${mysql_port}/spring_cloud_demo?useUnicode=true&useSSL=false&amp;characterEncoding=utf8
    username: ${mysql_user}
    password: ${mysql_password}
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1