server:
  port: 8002

zuul:
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie
  retryable: true
  routes:
    auth:
      path: /uaa/**
      service-id: auth
      strip-prefix: false
    user:
      path: /users/**
      service-id: user
      strip-prefix: false
    product:
      path: /products/**
      service-id: product
      strip-prefix: false
    order:
      path: /orders/**
      service-id: order
      strip-prefix: false

logging:
  level:
    org.springframework.security: DEBUG

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 80000

---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0

security:
  oauth2:
    client:
      client-id: api
      client-secret: secret
      access-token-uri: http://localhost:9999/uaa/oauth/token
      user-authorization-uri: http://localhost:9999/uaa/oauth/authorize
    resource:
      token-info-uri: http://localhost:9999/uaa/oauth/check_token

---
spring:
  profiles: test
  redis:
    host: ${REDIS_SERVICE_HOST}
    port: ${REDIS_SERVICE_PORT}
    database: 0
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0

security:
  oauth2:
    client:
      client-id: api
      client-secret: secret
      access-token-uri: http://oauth:9999/uaa/oauth/token
      user-authorization-uri: http://oauth:9999/uaa/oauth/authorize
    resource:
      token-info-uri: http://oauth:9999/uaa/oauth/check_token