server:
  port: 9103

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  default-schema: spring_cloud_demo
  drop-first: false
  enabled: true

spring:
  cloud:
    stream:
      bindings:
        cancel_reservation_output:
          binder: rabbit
          destination: cancel-reservation
          group: default
          content-type: application/json
          producer:
            required-groups: default
        waiting_payment_output:
          binder: rabbit
          destination: waiting-payment
          group: default
          content-type: application/json
          producer:
            required-groups: default
        payment_succeeded_input:
          binder: rabbit
          destination: payment-succeeded
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3
        waiting_payment_input:
          binder: rabbit
          destination: waiting-payment
          group: default
          content-type: application/json
          consumer:
            max-attempts: 3
        payment_succeeded_output:
          binder: rabbit
          destination: payment-succeeded
          group: default
          content-type: application/json
          producer:
            required-groups: default
        reward_points_output:
          binder: rabbit
          destination: reward-points
          group: default
          content-type: application/json
          producer:
            required-groups: default
    loadbalancer:
      retry:
        enabled: true

product:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2

---
spring:
  profiles: development

---
spring:
  profiles: k8s